name: Set up Nix and Cachix
description: Install and configure Nix and Cachix

inputs:
  github_token:
    description: GitHub token for API requests
    required: true
  cachix_token:
    description: Cachix token for pushing paths

runs:
  using: composite

  steps:
    - uses: cachix/install-nix-action@b95f68250363e6996e0fdafe18cf23c3fc9f873b
      with:
        github_access_token: ${{ inputs.github_token }}

    - uses: cachix/cachix-action@v12
      if: ${{ inputs.cachix_token != '' }}
      with:
        name: internetunexplorer
        authToken: ${{ inputs.cachix_token }}
        pushFilter: "-source$"
