name: Set up Nix and Cachix
description: Install and configure Nix and Cachix

inputs:
  cachix_token:
    description: Cachix token for pushing paths

runs:
  using: composite

  steps:
    - uses: cachix/install-nix-action@v19

    - uses: cachix/cachix-action@v12
      if: ${{ inputs.cachix_token != '' }}
      with:
        name: internetunexplorer
        authToken: ${{ inputs.cachix_token }}
        pushFilter: "-source$"
