name: Check for package updates

on:
  schedule:
    - cron: 0 14 * * * # Every day at 2PM
  workflow_dispatch:

concurrency: update

defaults:
  run:
    shell: bash # Enables '-eo pipefail'

jobs:
  matrix:
    name: Generate update matrix
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.matrix.outputs.packages }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set-up-nix-and-cachix

      - id: matrix
        run: ./update.py matrix | tee $GITHUB_STEP_SUMMARY

  update:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: matrix

    if: needs.matrix.outputs.packages != '[]'

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.packages) }}
      max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set-up-nix-and-cachix
        with:
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: update
        run: ./update.py update ${{ matrix.package }} | tee $GITHUB_STEP_SUMMARY

      # Avoid creating a pull request if one already exists
      - name: Check for existing pull request
        id: check-existing
        if: steps.update.outputs.pr-title != ''
        run: echo "rev=$(git ls-remote origin ${{ fromJson(steps.update.outputs.pr-branch) }})" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        if: steps.update.outputs.pr-title != '' && steps.check-existing.outputs.rev == ''
        with:
          token: ${{ secrets.REPO_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ fromJson(steps.update.outputs.pr-branch) }}
          title: ${{ fromJson(steps.update.outputs.pr-title) }}
          labels: automated-update
          body: ${{ fromJson(steps.update.outputs.pr-body) }}
          commit-message: |
            ${{ fromJson(steps.update.outputs.pr-title) }}

            ${{ fromJson(steps.update.outputs.pr-body) }}
